/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Comments_Query.graphql
 * @generated SignedSource<<2d0afef7e0ec7b89169437a7679fa4f3>>
 * @relayHash 8dcc292281cca65b255f81c760365797
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query Comments_Query(
  $id: ID!
) {
  comments(post: $id) {
    ...Comments_comments
  }
}

fragment Comments_comments on CommentCollection {
  results(first: $total) {
    edges {
      node {
        id
        author_name
        author_url
        date
        content {
          rendered
        }
        author_avatar_urls {
          size
          url
        }
        parent
      }
    }
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "id",
        "type": "ID!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "Comments_Query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "post",
            "variableName": "id",
            "type": "ID"
          }
        ],
        "concreteType": "CommentCollection",
        "name": "comments",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "Comments_comments",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "Comments_Query",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "id",
        "type": "ID!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "Comments_Query",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "post",
            "variableName": "id",
            "type": "ID"
          }
        ],
        "concreteType": "CommentCollection",
        "name": "comments",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": [
              {
                "kind": "Variable",
                "name": "first",
                "variableName": "total",
                "type": "Int"
              }
            ],
            "concreteType": "CommentConnection",
            "name": "results",
            "plural": false,
            "selections": [
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "CommentEdge",
                "name": "edges",
                "plural": true,
                "selections": [
                  {
                    "kind": "LinkedField",
                    "alias": null,
                    "args": null,
                    "concreteType": "Comment",
                    "name": "node",
                    "plural": false,
                    "selections": [
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "id",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "author_name",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "author_url",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "date",
                        "storageKey": null
                      },
                      {
                        "kind": "LinkedField",
                        "alias": null,
                        "args": null,
                        "concreteType": "Content",
                        "name": "content",
                        "plural": false,
                        "selections": [
                          {
                            "kind": "ScalarField",
                            "alias": null,
                            "args": null,
                            "name": "rendered",
                            "storageKey": null
                          }
                        ],
                        "storageKey": null
                      },
                      {
                        "kind": "LinkedField",
                        "alias": null,
                        "args": null,
                        "concreteType": "Avatar",
                        "name": "author_avatar_urls",
                        "plural": true,
                        "selections": [
                          {
                            "kind": "ScalarField",
                            "alias": null,
                            "args": null,
                            "name": "size",
                            "storageKey": null
                          },
                          {
                            "kind": "ScalarField",
                            "alias": null,
                            "args": null,
                            "name": "url",
                            "storageKey": null
                          }
                        ],
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "parent",
                        "storageKey": null
                      }
                    ],
                    "storageKey": null
                  }
                ],
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query Comments_Query(\n  $id: ID!\n) {\n  comments(post: $id) {\n    ...Comments_comments\n  }\n}\n\nfragment Comments_comments on CommentCollection {\n  results(first: $total) {\n    edges {\n      node {\n        id\n        author_name\n        author_url\n        date\n        content {\n          rendered\n        }\n        author_avatar_urls {\n          size\n          url\n        }\n        parent\n      }\n    }\n  }\n}\n"
};

module.exports = batch;
