/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Tag_Query.graphql
 * @generated SignedSource<<26e238f6dcdef60c544eb51957683ae6>>
 * @relayHash 8ad3c4a4cae6294adc532f5dbde055f3
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query Tag_Query(
  $id: ID!
) {
  tag(id: $id) {
    ...Tag_term
    id
  }
}

fragment Tag_term on TermInterface {
  id
  name
  taxonomy {
    slug
    id
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "id",
        "type": "ID!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "Tag_Query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "id",
            "variableName": "id",
            "type": "ID"
          }
        ],
        "concreteType": "Tag",
        "name": "tag",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "Tag_term",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "Tag_Query",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "id",
        "type": "ID!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "Tag_Query",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "id",
            "variableName": "id",
            "type": "ID"
          }
        ],
        "concreteType": "Tag",
        "name": "tag",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "name",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Taxonomy",
            "name": "taxonomy",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "slug",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query Tag_Query(\n  $id: ID!\n) {\n  tag(id: $id) {\n    ...Tag_term\n    id\n  }\n}\n\nfragment Tag_term on TermInterface {\n  id\n  name\n  taxonomy {\n    slug\n    id\n  }\n}\n"
};

module.exports = batch;
