/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule App_viewer.graphql
 * @generated SignedSource<<2670d8350f773017d3fa0a6fe37c236d>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type App_viewer = {|
  +navMenu: ?{| |};
  +sidebar: ?{| |};
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "RootArgument",
      "name": "menuID",
      "type": "ID"
    },
    {
      "kind": "RootArgument",
      "name": "sidebarID",
      "type": "ID"
    }
  ],
  "kind": "Fragment",
  "metadata": null,
  "name": "App_viewer",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Variable",
          "name": "id",
          "variableName": "menuID",
          "type": "ID"
        }
      ],
      "concreteType": "NavMenu",
      "name": "navMenu",
      "plural": false,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "NavMenu_navMenu",
          "args": null
        }
      ],
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Variable",
          "name": "id",
          "variableName": "sidebarID",
          "type": "ID"
        }
      ],
      "concreteType": "Sidebar",
      "name": "sidebar",
      "plural": false,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "Sidebar_sidebar",
          "args": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
