/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Comments_comments.graphql
 * @generated SignedSource<<8e5b3f91a627b74861312e3bd6e99258>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Comments_comments = {| |};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Comments_comments",
  "selections": [
    {
      "kind": "FragmentSpread",
      "name": "Walker_comments",
      "args": null
    }
  ],
  "type": "CommentEdge"
};

module.exports = fragment;
