/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Home_viewer.graphql
 * @generated SignedSource<<930f8caf592fecf3e291a53c6cf1def9>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Home_viewer = {|
  +readThis: ?{| |};
  +watchThis: ?{| |};
  +listenToThis: ?{| |};
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "RootArgument",
      "name": "readThisID",
      "type": "String"
    },
    {
      "kind": "RootArgument",
      "name": "watchThisID",
      "type": "String"
    },
    {
      "kind": "RootArgument",
      "name": "listenToThisID",
      "type": "String"
    }
  ],
  "kind": "Fragment",
  "metadata": null,
  "name": "Home_viewer",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": "readThis",
      "args": [
        {
          "kind": "Variable",
          "name": "categories",
          "variableName": "readThisID",
          "type": "String"
        },
        {
          "kind": "Literal",
          "name": "last",
          "value": 5,
          "type": "Int"
        }
      ],
      "concreteType": "PostConnection",
      "name": "posts",
      "plural": false,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "Archive_posts",
          "args": null
        }
      ],
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": "watchThis",
      "args": [
        {
          "kind": "Variable",
          "name": "categories",
          "variableName": "watchThisID",
          "type": "String"
        },
        {
          "kind": "Literal",
          "name": "last",
          "value": 5,
          "type": "Int"
        }
      ],
      "concreteType": "PostConnection",
      "name": "posts",
      "plural": false,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "Archive_posts",
          "args": null
        }
      ],
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": "listenToThis",
      "args": [
        {
          "kind": "Variable",
          "name": "categories",
          "variableName": "listenToThisID",
          "type": "String"
        },
        {
          "kind": "Literal",
          "name": "last",
          "value": 5,
          "type": "Int"
        }
      ],
      "concreteType": "PostConnection",
      "name": "posts",
      "plural": false,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "Archive_posts",
          "args": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
