/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Tag_term.graphql
 * @generated SignedSource<<7d278de1baf02c7dff087d5ee89f758e>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Tag_term = {
  id: string;
  name?: ?string;
  taxonomy?: ?Tag_term_taxonomy;
};

export type Tag_term_taxonomy = {
  slug?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Tag_term",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "name",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Taxonomy",
      "name": "taxonomy",
      "plural": false,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "slug",
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "TermInterface"
};

module.exports = fragment;
