/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Media_media.flow
 * @generated SignedSource<<a5a8b795b2728530dcbe81fcae6d5a47>>
 * @flow
 */

'use strict';

export type Media_media = {
  __typename: string;
};
