/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Term_term.flow
 * @generated SignedSource<<44cd1bd13be18c49d5d7fa06ad42bc38>>
 * @flow
 */

'use strict';

export type Term_term = {
  id: string;
  name?: ?string;
  taxonomy?: ?Term_term_taxonomy;
};

export type Term_term_taxonomy = {
  slug?: ?string;
};
