/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Term_posts.graphql
 * @generated SignedSource<<cb3138eade670e27a7c580a7fad54d23>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Term_posts = { };
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Term_posts",
  "selections": [
    {
      "kind": "FragmentSpread",
      "name": "Archive_posts",
      "args": null
    }
  ],
  "type": "PostCollection"
};

module.exports = fragment;
