/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule TagArchive_posts.graphql
 * @generated SignedSource<<ad2d37c1c7c2c2749630551d792ad7f0>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type TagArchive_posts = {
  results?: ?TagArchive_posts_results;
};

export type TagArchive_posts_results_edges_node = {
  id: string;
};

export type TagArchive_posts_results_edges = {
  node?: ?TagArchive_posts_results_edges_node;
  cursor: string;
};

export type TagArchive_posts_results = {
  edges?: ?Array<?TagArchive_posts_results_edges>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "RootArgument",
      "name": "count",
      "type": "Int"
    },
    {
      "kind": "RootArgument",
      "name": "cursor",
      "type": "String"
    }
  ],
  "kind": "Fragment",
  "metadata": {
    "connection": [
      {
        "count": "count",
        "cursor": "cursor",
        "direction": "forward",
        "path": [
          "results"
        ]
      }
    ]
  },
  "name": "TagArchive_posts",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": "results",
      "args": null,
      "concreteType": "PostConnection",
      "name": "__TagArchive_results_connection",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "PostEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Post",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "FragmentSpread",
                  "name": "Post_post",
                  "args": null
                }
              ],
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "cursor",
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "PostCollection"
};

module.exports = fragment;
