/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Single_comments.graphql
 * @generated SignedSource<<3d930843870140167b4f4a2d6517df9d>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Single_comments = { };
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Single_comments",
  "selections": [
    {
      "kind": "FragmentSpread",
      "name": "Comments_comments",
      "args": null
    }
  ],
  "type": "CommentCollection"
};

module.exports = fragment;
