/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Single_comments.flow
 * @generated SignedSource<<12f02bd5db1670c8bb635875088d8f7a>>
 * @flow
 */

'use strict';

export type Single_comments = { };
