/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule NavMenu_navMenu.flow
 * @generated SignedSource<<69013676b100ebbdf4bea41f495b50a6>>
 * @flow
 */

'use strict';

export type NavMenu_navMenu = {
  id: string;
  name?: ?string;
  items?: ?Array<?NavMenu_navMenu_items>;
};

export type NavMenu_navMenu_items = {
  id?: ?string;
  title?: ?string;
  url?: ?string;
  parent?: ?string;
  order?: ?number;
  object?: ?string;
  object_id?: ?string;
};
