/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule NavMenu_menu.graphql
 * @generated SignedSource<<1605b021b98baa080aab330cfd9138a1>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type NavMenu_menu = {
  id: string;
  name?: ?string;
  items?: ?Array<?NavMenu_menu_items>;
};

export type NavMenu_menu_items = {
  id?: ?string;
  title?: ?string;
  url?: ?string;
  parent?: ?string;
  order?: ?number;
  object?: ?string;
  object_id?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "NavMenu_menu",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "name",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "NavMenuItem",
      "name": "items",
      "plural": true,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "id",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "title",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "url",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "parent",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "order",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "object",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "object_id",
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "NavMenu"
};

module.exports = fragment;
