/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Comments_comments.graphql
 * @generated SignedSource<<3ad06fe936c3f7dc1f276f64858e470a>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Comments_comments = {
  results?: ?Comments_comments_results;
};

export type Comments_comments_results_edges_node_content = {
  rendered?: ?string;
};

export type Comments_comments_results_edges_node_author_avatar_urls = {
  size?: ?number;
  url?: ?string;
};

export type Comments_comments_results_edges_node = {
  id: string;
  author_name?: ?string;
  author_url?: ?string;
  date?: ?string;
  content?: ?Comments_comments_results_edges_node_content;
  author_avatar_urls?: ?Array<?Comments_comments_results_edges_node_author_avatar_urls>;
  parent?: ?string;
};

export type Comments_comments_results_edges = {
  node?: ?Comments_comments_results_edges_node;
};

export type Comments_comments_results = {
  edges?: ?Array<?Comments_comments_results_edges>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "RootArgument",
      "name": "total",
      "type": "Int"
    }
  ],
  "kind": "Fragment",
  "metadata": null,
  "name": "Comments_comments",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Variable",
          "name": "first",
          "variableName": "total",
          "type": "Int"
        }
      ],
      "concreteType": "CommentConnection",
      "name": "results",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "CommentEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Comment",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "author_name",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "author_url",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "date",
                  "storageKey": null
                },
                {
                  "kind": "LinkedField",
                  "alias": null,
                  "args": null,
                  "concreteType": "Content",
                  "name": "content",
                  "plural": false,
                  "selections": [
                    {
                      "kind": "ScalarField",
                      "alias": null,
                      "args": null,
                      "name": "rendered",
                      "storageKey": null
                    }
                  ],
                  "storageKey": null
                },
                {
                  "kind": "LinkedField",
                  "alias": null,
                  "args": null,
                  "concreteType": "Avatar",
                  "name": "author_avatar_urls",
                  "plural": true,
                  "selections": [
                    {
                      "kind": "ScalarField",
                      "alias": null,
                      "args": null,
                      "name": "size",
                      "storageKey": null
                    },
                    {
                      "kind": "ScalarField",
                      "alias": null,
                      "args": null,
                      "name": "url",
                      "storageKey": null
                    }
                  ],
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "parent",
                  "storageKey": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "CommentCollection"
};

module.exports = fragment;
