/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Image_image.flow
 * @generated SignedSource<<094b7ad33b6f004d0a1c65a4a5bc257b>>
 * @flow
 */

'use strict';

export type Image_image = {
  source_url?: ?string;
  media_details?: ?Image_image_media_details;
};

export type Image_image_media_details_sizes = {
  name?: ?string;
  source_url?: ?string;
};

export type Image_image_media_details = {
  sizes?: ?Array<?Image_image_media_details_sizes>;
};
