/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Media_media.graphql
 * @generated SignedSource<<a05d1fb92000cfe3b06a15df024f9ac1>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Media_media = {
  __typename: string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Media_media",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "__typename",
      "storageKey": null
    },
    {
      "kind": "FragmentSpread",
      "name": "Image_image",
      "args": null
    }
  ],
  "type": "Media"
};

module.exports = fragment;
