/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Sidebar_sidebar.flow
 * @generated SignedSource<<2ef546d58a9945b623497939500d3cdc>>
 * @flow
 */

'use strict';

export type Sidebar_sidebar = {
  widgets?: ?Array<?Sidebar_sidebar_widgets>;
};

export type Sidebar_sidebar_widgets_content = {
  rendered?: ?string;
};

export type Sidebar_sidebar_widgets = {
  classname?: ?string;
  content?: ?Sidebar_sidebar_widgets_content;
};
