/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Sidebar_sidebar.graphql
 * @generated SignedSource<<15055806fd07f8a5df1bf8fae2eecdce>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Sidebar_sidebar = {
  widgets?: ?Array<?Sidebar_sidebar_widgets>;
};

export type Sidebar_sidebar_widgets_content = {
  rendered?: ?string;
};

export type Sidebar_sidebar_widgets = {
  classname?: ?string;
  content?: ?Sidebar_sidebar_widgets_content;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Sidebar_sidebar",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Widget",
      "name": "widgets",
      "plural": true,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "classname",
          "storageKey": null
        },
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "Content",
          "name": "content",
          "plural": false,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "rendered",
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Sidebar"
};

module.exports = fragment;
