/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Ambiguous_year.graphql
 * @generated SignedSource<<54724ac7e5a2e471727943bb02b3c0c4>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Ambiguous_year = { };
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Ambiguous_year",
  "selections": [
    {
      "kind": "FragmentSpread",
      "name": "Archive_posts",
      "args": null
    }
  ],
  "type": "PostCollection"
};

module.exports = fragment;
