/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Page_page.flow
 * @generated SignedSource<<34aab92df9bb05ff47a19e63cdc6d50d>>
 * @flow
 */

'use strict';

export type Page_page = {
  id: string;
  slug?: ?string;
  title?: ?Page_page_title;
  content?: ?Page_page_content;
  featured_media?: ?any;
};

export type Page_page_title = {
  rendered?: ?string;
};

export type Page_page_content = {
  rendered?: ?string;
};
