/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Term_posts.flow
 * @generated SignedSource<<59e649fa4e17feeb100038be251eb861>>
 * @flow
 */

'use strict';

export type Term_posts = { };
