/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Archive_edges.graphql
 * @generated SignedSource<<a6648f81e117c485eeafd3eaed3c40d9>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Archive_edges = {|
  +node: ?{| |};
  +cursor: string;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Archive_edges",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Post",
      "name": "node",
      "plural": false,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "Post_post",
          "args": null
        }
      ],
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "cursor",
      "storageKey": null
    }
  ],
  "type": "PostEdge"
};

module.exports = fragment;
