/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Author_author.graphql
 * @generated SignedSource<<2f48d721c47155b5dd4186576c0fb88c>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Author_author = {
  name?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Author_author",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "name",
      "storageKey": null
    }
  ],
  "type": "User"
};

module.exports = fragment;
