/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Author_posts.flow
 * @generated SignedSource<<330e2dbc4369987f1405df4f1fd75312>>
 * @flow
 */

'use strict';

export type Author_posts = { };
