/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Post_post.flow
 * @generated SignedSource<<bb9a81d763a18bdab69bfc00eed3d26d>>
 * @flow
 */

'use strict';

export type Post_post = {
  id: string;
  title?: ?Post_post_title;
  content?: ?Post_post_content;
  excerpt?: ?Post_post_excerpt;
  featured_media?: ?any;
};

export type Post_post_title = {
  rendered?: ?string;
};

export type Post_post_content = {
  rendered?: ?string;
};

export type Post_post_excerpt = {
  rendered?: ?string;
};
