/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Ambiguous_page.graphql
 * @generated SignedSource<<31b093d5127a148fbb91a3279ce89de6>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Ambiguous_page = { };
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Ambiguous_page",
  "selections": [
    {
      "kind": "FragmentSpread",
      "name": "Page_page",
      "args": null
    }
  ],
  "type": "Page"
};

module.exports = fragment;
