/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Ambiguous_page.flow
 * @generated SignedSource<<c13303c85bfc9ca2a238af77fd2fcda1>>
 * @flow
 */

'use strict';

export type Ambiguous_page = { };
