/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Ambiguous_year.flow
 * @generated SignedSource<<db6583ed60364897c4cdd8fc2b4eee18>>
 * @flow
 */

'use strict';

export type Ambiguous_year = { };
